export interface IAcars1 {
	Timestamp: string,
	ICAO: string,
	Rego: string,
	Type: string,
	Year: string,
	Interest: string,
	Desc: string,
	Owner: string,
	ADSBEx: string,
	Raw: string,
	Sat: string,
}

export interface IAcars2 {
	Timestamp: string,
	Flight: string,
	Call: string,
	Tail: string,
	Type: string,
	Desc: string,
	ICAOtxt: string,
	ICAO: string,
	AES: string,
	sat: string,
	gndstn: string,
	Raw: string,
}

export interface IAcars3 {
	Timestamp: string,
	Realtime: number,
	icao: string,
	Rego: string,
	Flight: string,
	EPtime: number,
	Type: string,
	Year: string,
	Desc: string,
	Owner: string,
	Alt: number,
	Speed: number,
	ADSBEx: string,
}

export interface IAcars4 {
	timest: string,
	icao: string,
	callsign: string,
	rego: string,
	actype: string,
	depart: string,
	arrive: string,
	mission: string,
	sat: string,
	inserted: string,
	mc1: string,
	mc2: string,
	mc3: string,
	mc4: string,
	adsbex: string,
	skyvect: string,
	mcs: string,
	mc22: string,
	departloc: string,
	arriveloc: string,
	rawacars: string,
}

export interface IAcars5 {
	Timestamp: string,
	Tail: string,
	call: string,
	ID: string,
	Sat: string,
	mcs: string,
	Type: string,
	DD: string,
	DT: string,
	UT: string,
	departloc: string,
	depart: string,
	arrive: string,
	arriveloc: string,
	Mission: string,
	Desc: string,
	ICAOtxt: string,
	ICAO: string,
	Skyvec: string,
	Raw: string,
}

export type AllAcars = IAcars1 | IAcars2 | IAcars3 | IAcars4 | IAcars5;