import type { Metadata } from 'next'
import './globals.scss'
import { ReduxProvider } from '@/redux/provider'
//=========================================================================================================================

export const metadata: Metadata = {
	title: 'Acars App',
	description: 'Generated by NextJS',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<ReduxProvider>
			<html lang="en">
				<body >{children}</body>
			</html>
		</ReduxProvider>
	)
}
